configMap:
  region: "aarika"
  access_key: "baobab"
  access_secret: "coccis"
  env: "dev"


secret:
  region: "YWFyaWthCg=="
  access_key: "YmFvYmFiCg=="
  access_secret: "Y29jY2lzCg=="


deployment:
  replicaCount: 1
  imagePullSecrets: wework-registry
  image:
    repository: nginx
    pullPolicy: Always
    tag: "1.17"
  ports:
    - name: api
      containerPort: 80
    - name: health
      containerPort: 9090
  livenessProbe:
    httpGet:
      path: /
      port: api
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /
      port: api
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi


service:
  type: ClusterIP
  port: 8080
  name: api
  targetPort: api


ingress:
  enabled: true
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: appdemo.wework.cn
      paths:
        - "/"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local